In [2]:
import pandas as pd
df =pd.read_csv("SuperMarket.csv")
df.shape

(1014, 17)

In [3]:
##1014 Rows 17 Coloumns
print(df.shape)

(1014, 17)

In [4]:
df.isnull().sum()

Invoice ID                  0
Branch                      0
City                        0
   Customer type            0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
   cogs                     0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(14)

In [6]:
df.describe()

,Unit price,Quantity,Tax 5%,cogs,gross margin percentage,gross income,Rating
count,990.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000
mean,55.520333,5.502959,15.336872,306.737436,4.761905,15.336872,6.960454
std,26.330508,2.927133,11.685945,233.718896,0.000000,11.685945,1.721264
min,10.080000,1.000000,0.508500,10.170000,4.761905,0.508500,4.000000
25%,33.202500,3.000000,5.864625,117.292500,4.761905,5.864625,5.500000
50%,54.890000,5.000000,12.066000,241.320000,4.761905,12.066000,6.900000
75%,77.667500,8.000000,22.428000,448.560000,4.761905,22.428000,8.475000
max,99.960000,10.000000,49.650000,993.000000,4.761905,49.650000,10.000000

In [7]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Invoice ID,1014,1000,518-17-2983,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Branch,1014,8,Alex,341,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,1014,3,Yangon,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer type,1014,2,Member,570,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,1014,4,Female,566,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product line,1014,6,Fashion accessories,181,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unit price,990.0,NaN,NaN,NaN,55.520333,26.330508,10.08,33.2025,54.89,77.6675,99.96
Quantity,1014.0,NaN,NaN,NaN,5.502959,2.927133,1.0,3.0,5.0,8.0,10.0
Tax 5%,1014.0,NaN,NaN,NaN,15.336872,11.685945,0.5085,5.864625,12.066,22.428,49.65
Sales,994,970,829.08,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,1002,89,2/15/2019,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,1014,506,7:48:00 PM,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment,1014,6,Ewallet,351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cogs,1014.0,NaN,NaN,NaN,306.737436,233.718896,10.17,117.2925,241.32,448.56,993.0
gross margin percentage,1014.0,NaN,NaN,NaN,4.761905,0.0,4.761905,4.761905,4.761905,4.761905,4.761905
gross income,1014.0,NaN,NaN,NaN,15.336872,11.685945,0.5085,5.864625,12.066,22.428,49.65
Rating,1014.0,NaN,NaN,NaN,6.960454,1.721264,4.0,5.5,6.9,8.475,10.0

In [8]:
for column in df.select_dtypes(include="object").columns:
    print("\n", column)
    print(df[column].unique())

 Invoice ID
<StringArray>
['750-67-8428', '226-31-3081', '631-41-3108', '123-19-1176', '373-73-7910',
 '699-14-3026', '355-53-5943', '315-22-5665', '665-32-9167', '692-92-5582',
 ...
 '886-18-2897', '602-16-6955', '745-74-0715', '690-01-6631', '652-49-6720',
 '233-67-5758', '303-96-2227', '727-02-1313', '347-56-2442', '849-09-3807']
Length: 1000, dtype: str

 Branch
<StringArray>
[              'Alex',               'Giza',              'Cairo',
         '     Cairo',               'giza',              'cairo',
 '      Cairo       ',          'Alex     ']
Length: 8, dtype: str

 City
<StringArray>
['Yangon', 'Naypyitaw', 'Mandalay']
Length: 3, dtype: str

    Customer type
<StringArray>
['Member', 'Normal']
Length: 2, dtype: str

 Gender
<StringArray>
['Female', 'F', 'Male', 'M']
Length: 4, dtype: str

 Product line
<StringArray>
[     'Health and beauty', 'Electronic accessories',     'Home and lifestyle',
      'Sports and travel',     'Food and beverages',    'Fashion accessories']
Length: 6, dtype: str

 Sales
<StringArray>
['548.9715',    '80.22', '340.5255',  '489.048', '634.3785', '627.6165',
  '433.692',   '772.38',   '76.146',  '172.746',
 ...
   '296.94',    '804.3',  '121.863',  '183.645',  '63.9975',  '42.3675',
  '1022.49',   '33.432',   '69.111',  '649.299']
Length: 971, dtype: str

 Date
<StringArray>
[ '1/5/2019',  '3/8/2019',  '3/3/2019', '1/27/2019',         nan, '3/11/2019',
  '1/1/2019', '1/21/2019', '2/25/2019',  '3/5/2019', '3/15/2019', '2/17/2019',
  '3/2/2019', '3/22/2019',  '2/8/2019', '3/10/2019', '1/25/2019', '1/28/2019',
 '1/10/2019',  '2/6/2019',  '1/7/2019', '1/15/2019', '3/23/2019', '1/17/2019',
  '2/2/2019',  '3/4/2019', '3/16/2019',  '3/9/2019', '2/27/2019', '2/10/2019',
 '3/19/2019',  '2/3/2019',  '3/7/2019', '2/28/2019', '3/27/2019',  '2/7/2019',
 '1/20/2019', '3/12/2019', '2/15/2019', '2/24/2019',  '3/6/2019', '2/14/2019',
 '3/13/2019', '1/24/2019',  '1/6/2019', '2/11/2019', '1/22/2019', '1/13/2019',
  '1/9/2019', '1/12/2019', '1/26/2019', '1/23/2019', '2/23/2019', '3/25/2019',
  '1/2/2019', '3/29/2019',  '2/9/2019', '3/26/2019',  '3/1/2019',  '2/1/2019',
 '3/28/2019', '3/24/2019',  '2/5/2019', '1/19/2019', '1/16/2019',  '1/8/2019',
 '2/18/2019', '1/18/2019', '2/16/2019', '2/22/2019', '1/29/2019', '2/20/2019',
  '1/4/2019', '3/30/2019', '1/30/2019',  '1/3/2019', '3/21/2019', '2/13/2019',
 '1/14/2019', '3/18/2019', '3/20/2019', '2/21/2019', '2/12/2019', '1/31/2019',
 '1/11/2019', '2/26/2019', '3/17/2019', '3/14/2019',  '2/4/2019', '2/19/2019']
Length: 90, dtype: str

 Time
<StringArray>
[ '1:08:00 PM', '10:29:00 AM',  '1:23:00 PM',  '8:33:00 PM', '10:37:00 AM',
  '6:30:00 PM',  '2:36:00 PM', '11:38:00 AM',  '5:15:00 PM',  '1:27:00 PM',
 ...
 '10:58:00 AM',  '1:49:00 PM', '11:10:00 AM',  '1:33:00 PM',  '2:05:00 PM',
  '4:27:00 PM',  '3:23:00 PM',  '6:18:00 PM',  '3:17:00 PM',  '7:12:00 PM']
Length: 506, dtype: str

 Payment
<StringArray>
['Ewallet', 'Cash', 'Credit card', 'E-wallet', 'credit card', 'cash']
Length: 6, dtype: str

C:\Users\Hello\AppData\Local\Temp\ipykernel_23984\1618711878.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unit price,990.0,55.520333,26.330508,10.080000,33.202500,54.890000,77.667500,99.960000
Quantity,1014.0,5.502959,2.927133,1.000000,3.000000,5.000000,8.000000,10.000000
Tax 5%,1014.0,15.336872,11.685945,0.508500,5.864625,12.066000,22.428000,49.650000
cogs,1014.0,306.737436,233.718896,10.170000,117.292500,241.320000,448.560000,993.000000
gross margin percentage,1014.0,4.761905,0.000000,4.761905,4.761905,4.761905,4.761905,4.761905
gross income,1014.0,15.336872,11.685945,0.508500,5.864625,12.066000,22.428000,49.650000
Rating,1014.0,6.960454,1.721264,4.000000,5.500000,6.900000,8.475000,10.000000

In [10]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace("%", "percent", regex=False)
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

print(df.columns.tolist())

['invoice_id', 'branch', 'city', 'customer_type', 'gender', 'product_line', 'unit_price', 'quantity', 'tax_5percent', 'sales', 'date', 'time', 'payment', 'cogs', 'gross_margin_percentage', 'gross_income', 'rating']

In [11]:
text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    df[column] = df[column].astype("string").str.strip()

C:\Users\Hello\AppData\Local\Temp\ipykernel_23984\2786429840.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

In [14]:
df["payment"] = df["payment"].replace({
    "E-wallet": "Ewallet",
    "credit card": "Credit card",
    "cash": "Cash"
})

df["payment"].value_counts()

payment
Ewallet        355
Cash           345
Credit card    314
Name: count, dtype: Int64

In [16]:
df["sales"] = (
    df["sales"]
    .astype("string")
    .str.replace("EGP", "", regex=False)
    .str.strip()
)

df["sales"] = pd.to_numeric(df["sales"], errors="coerce")

df["sales"].head()

0    548.9715
1       80.22
2    340.5255
3     489.048
4    634.3785
Name: sales, dtype: Float64

In [17]:
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

df["date"].head()

0   2019-01-05
1   2019-03-08
2   2019-03-03
3   2019-01-27
4          NaT
Name: date, dtype: datetime64[us]

In [18]:
print(df.isnull().sum())

invoice_id                  0
branch                      0
city                        0
customer_type               0
gender                      0
product_line                0
unit_price                 24
quantity                    0
tax_5percent                0
sales                      20
date                       12
time                        0
payment                     0
cogs                        0
gross_margin_percentage     0
gross_income                0
rating                      0
dtype: int64

In [20]:
df["unit_price"] = df["unit_price"].fillna(
    df["unit_price"].median()
)

df["sales"] = df["sales"].fillna(
    df["sales"].median()
)

In [21]:
df["date"] = df["date"].ffill().bfill()

In [22]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 14
Duplicates after: 0

In [23]:
df = df.drop(columns=["invoice_id"])

df.head()

,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5percent,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.22,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.048,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-01-27,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [26]:
df = df.sort_values(
    by=["date", "time"]
).reset_index(drop=True)

df.head()

,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5percent,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,Alex,Yangon,Member,Female,Sports and travel,72.61,6,21.783,457.443,2019-01-01,10:39:00 AM,Credit card,435.66,4.761905,21.783,6.9
1,Cairo,Mandalay,Member,Female,Food and beverages,84.63,10,42.315,888.615,2019-01-01,11:36:00 AM,Credit card,846.30,4.761905,42.315,9.0
2,Giza,Naypyitaw,Member,Female,Sports and travel,29.22,6,8.766,184.086,2019-01-01,11:40:00 AM,Ewallet,175.32,4.761905,8.766,5.0
3,Giza,Naypyitaw,Normal,Male,Health and beauty,62.87,2,6.287,132.027,2019-01-01,11:43:00 AM,Cash,125.74,4.761905,6.287,5.0
4,Alex,Yangon,Normal,Female,Fashion accessories,65.74,9,29.583,621.243,2019-01-01,1:55:00 PM,Cash,591.66,4.761905,29.583,7.7

In [27]:
df["day"] = df["date"].dt.day
df["month"] = df["date"].dt.month
df["year"] = df["date"].dt.year

df[["date", "day", "month", "year"]].head()

        date  day  month  year
0 2019-01-01    1      1  2019
1 2019-01-01    1      1  2019
2 2019-01-01    1      1  2019
3 2019-01-01    1      1  2019
4 2019-01-01    1      1  2019

In [29]:
print("Shape:", df.shape)

print("\nNull values:")
print(df.isnull().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (1000, 19)

Null values:
branch                     0
city                       0
customer_type              0
gender                     0
product_line               0
unit_price                 0
quantity                   0
tax_5percent               0
sales                      0
date                       0
time                       0
payment                    0
cogs                       0
gross_margin_percentage    0
gross_income               0
rating                     0
day                        0
month                      0
year                       0
dtype: int64

Duplicates:
0

Data types:
branch                             string
city                               string
customer_type                      string
gender                             string
product_line                       string
unit_price                        float64
quantity                            int64
tax_5percent                      float64
sales                             Float64
date                       datetime64[us]
time                               string
payment                            string
cogs                              float64
gross_margin_percentage           float64
gross_income                      float64
rating                            float64
day                                 int32
month                               int32
year                                int32
dtype: object

In [30]:
total_revenue = df["sales"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 319443.6315

In [31]:
revenue_by_city = (
    df.groupby("city")["sales"]
    .sum()
    .sort_values(ascending=False)
)

print(revenue_by_city)

print("\nCity with highest revenue:")
print(revenue_by_city.idxmax())

print("Highest revenue:")
print(revenue_by_city.max())

city
Naypyitaw    109107.3375
Mandalay     105602.8995
Yangon       104733.3945
Name: sales, dtype: Float64

City with highest revenue:
Naypyitaw
Highest revenue:
109107.3375

In [32]:
profit_by_branch = (
    df.groupby("branch")["gross_income"]
    .sum()
    .sort_values(ascending=False)
)

print(profit_by_branch)

print("\nMost profitable branch:")
print(profit_by_branch.idxmax())

print("Profit:")
print(profit_by_branch.max())

branch
Giza     5253.7765
Alex     5057.1605
Cairo    5022.1620
cairo      34.8700
giza       11.4000
Name: gross_income, dtype: float64

Most profitable branch:
Giza
Profit:
5253.7765

In [33]:
category_analysis = (
    df.groupby("product_line")
    .agg(
        total_revenue=("sales", "sum"),
        total_profit=("gross_income", "sum")
    )
    .sort_values(
        by="total_profit",
        ascending=False
    )
)

print(category_analysis)

print("\nTop-performing category:")
print(category_analysis.index[0])

                        total_revenue  total_profit
product_line
Food and beverages           55558.23     2673.5640
Sports and travel           54542.922     2624.8965
Electronic accessories     53702.8695     2587.5015
Fashion accessories         53544.456     2585.9950
Home and lifestyle         52963.9215     2564.8530
Health and beauty          49131.2325     2342.5590

Top-performing category:
Food and beverages

In [34]:
spending_by_customer_type = (
    df.groupby("customer_type")["sales"]
    .sum()
    .sort_values(ascending=False)
)

print(spending_by_customer_type)

print("\nCustomer type that spends more:")
print(spending_by_customer_type.idxmax())

customer_type
Member    186171.6465
Normal     133271.985
Name: sales, dtype: Float64

Customer type that spends more:
Member

In [35]:
transactions_by_payment = (
    df["payment"]
    .value_counts()
)

print(transactions_by_payment)

print("\nMost popular payment method:")
print(transactions_by_payment.idxmax())

payment
Ewallet        345
Cash           344
Credit card    311
Name: count, dtype: Int64

Most popular payment method:
Ewallet

In [36]:
average_transaction_value = df["sales"].mean()

print(
    "Average transaction value:",
    average_transaction_value
)

Average transaction value: 319.44363150000004

In [38]:
revenue_by_day = (
    df.groupby("day")["sales"]
    .sum()
    .sort_values(ascending=False)
)

print(revenue_by_day)

print("\nDay with highest sales:")
print(revenue_by_day.idxmax())

print("Revenue:")
print(revenue_by_day.max())

day
27    18482.7615
15    15301.9755
19    14883.2355
14     13570.116
9      13434.792
5     12898.7355
2      12880.392
8     12869.3985
23    12428.8185
3        12131.7
12    11674.8555
20    11140.5315
25     10719.261
17    10418.6145
7      10185.399
24     10157.175
10     9971.6505
16      9947.322
1      9824.0835
11     9218.9895
6       8951.628
28     8856.7815
26       8828.19
4      7957.6245
30     7045.3215
22     6873.4785
29     6790.3185
21     5663.3535
18     5569.3365
13     5535.2955
31     5232.4965
Name: sales, dtype: Float64

Day with highest sales:
27
Revenue:
18482.7615

In [40]:
revenue_by_month = (
    df.groupby("month")["sales"]
    .sum()
    .sort_values(ascending=False)
)

print(revenue_by_month)

print("\nMonth with highest sales:")
print(revenue_by_month.idxmax())

print("Revenue:")
print(revenue_by_month.max())

month
1     117967.647
3    108238.8825
2      93237.102
Name: sales, dtype: Float64

Month with highest sales:
1
Revenue:
117967.647