In [10]:
from flask import Flask, render_template

app = Flask(__name__)


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/projects")
def projects():
    return render_template("project.html")


if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [24/Sep/2026 03:06:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:06:48] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:06:52] "GET /projects HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:06:52] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:07:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:07:02] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:07:05] "GET /projects HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:07:05] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:07:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:07:07] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:09:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:09:05] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:09:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:09:07] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:09:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:09:08] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:09:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:09:08] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:09:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:09:08] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:09:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:09:09] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Sep/2026 03:09:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2026 03:09:10] "GET /static/style.css HTTP/1.1" 304 -

In [8]:
import pyodbc

ModuleNotFoundError: No module named 'pyodbc'

In [9]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading pyodbc-5.3.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (350 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pyodbc
pyodbc.drivers()

['ODBC Driver 18 for SQL Server']

In [15]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=your_server;"
    "DATABASE=your_database;"
    "UID=your_username;"
    "PWD=your_password;"
    "Encrypt=yes;"
    "TrustServerCertificate=yes;"
)

print("connected")

SystemError: <class 'pyodbc.Error'> returned a result with an exception set

In [17]:
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=127.0.0.1,1434;"
    "DATABASE=BankSystem;"
    "UID=sa;"
    "PWD=Moaaz2006@;"
    "Encrypt=yes;"
    "TrustServerCertificate=yes;"
    "Connection Timeout=10;"
)

print("connected successfully")

connected successfully

In [20]:
import pandas as pd
df = pd.read_sql_query("SELECT * FROM Customer", conn)
df

/tmp/ipykernel_62719/630503013.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM Customer", conn)

,CustomerID,Name,DateOfBirth,Gender,Address,PhoneNum,Email
0,201,Mohamed Hamed,1995-05-10,M,"Maadi, Cairo",01000000001,mohamed@gmail.com
1,202,Omar Khaled,1988-03-15,M,NaN,01000000002,NaN
2,203,Fatma Ali,1999-07-20,F,"Haram, Giza",01000000003,fatma@gmail.com
3,204,Nour Essam,2001-11-01,F,"Miami, Alexandria",01000000004,NaN
4,205,Karim Wael,1993-08-10,M,"Heliopolis, Cairo",01000000005,karim@gmail.com
5,206,Aya Reda,1997-02-18,F,"Zamalek, Cairo",01000000006,NaN
6,207,Mahmoud Fathy,1985-12-01,M,NaN,01000000007,mahmoud@gmail.com
7,208,Salma Sherif,2000-06-25,F,Tanta,01000000008,salma@gmail.com
8,209,Hany Ashraf,1990-09-09,M,Luxor,01000000009,NaN
9,210,Mariam Tarek,1998-04-14,F,Aswan,01000000010,mariam@gmail.com
10,211,Sherif Samy,1982-01-30,M,Ismailia,01000000011,sherif@gmail.com
11,212,Nadine Adel,1996-10-12,F,Port Said,01000000012,NaN
12,213,Tamer Youssef,1987-05-17,M,Sohag,01000000013,tamer@gmail.com
13,214,Rana Ali,1994-07-07,F,Beni Suef,01000000014,rana@gmail.com

In [23]:
def getID(id):
    id =int(id)
    df=pd.read_sql_query(f'execute p1 {id}',conn)
    return df

df.to_html

<bound method DataFrame.to_html of     CustomerID           Name DateOfBirth Gender            Address  \
0          201  Mohamed Hamed  1995-05-10      M       Maadi, Cairo
1          202    Omar Khaled  1988-03-15      M                NaN
2          203      Fatma Ali  1999-07-20      F        Haram, Giza
3          204     Nour Essam  2001-11-01      F  Miami, Alexandria
4          205     Karim Wael  1993-08-10      M  Heliopolis, Cairo
5          206       Aya Reda  1997-02-18      F     Zamalek, Cairo
6          207  Mahmoud Fathy  1985-12-01      M                NaN
7          208   Salma Sherif  2000-06-25      F              Tanta
8          209    Hany Ashraf  1990-09-09      M              Luxor
9          210   Mariam Tarek  1998-04-14      F              Aswan
10         211    Sherif Samy  1982-01-30      M           Ismailia
11         212    Nadine Adel  1996-10-12      F          Port Said
12         213  Tamer Youssef  1987-05-17      M              Sohag
13         214       Rana Ali  1994-07-07      F          Beni Suef

       PhoneNum              Email
0   01000000001  mohamed@gmail.com
1   01000000002                NaN
2   01000000003    fatma@gmail.com
3   01000000004                NaN
4   01000000005    karim@gmail.com
5   01000000006                NaN
6   01000000007  mahmoud@gmail.com
7   01000000008    salma@gmail.com
8   01000000009                NaN
9   01000000010   mariam@gmail.com
10  01000000011   sherif@gmail.com
11  01000000012                NaN
12  01000000013    tamer@gmail.com
13  01000000014     rana@gmail.com  >

In [24]:
getID(201)

/tmp/ipykernel_62719/1540689739.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query(f'execute p1 {id}',conn)

            name  balance
0  Mohamed Hamed  15000.0

In [39]:
from flask import Flask, render_template, request

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def home():

    table = None

    if request.method == "POST":
        id = request.form["customer_id"]

        df = getID(id)

        if not df.empty:
            table=df.to_html(index=False)

    return render_template("cst.html",table=table)

if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [24/Sep/2026 05:10:32] "GET / HTTP/1.1" 200 -
/tmp/ipykernel_62719/1540689739.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query(f'execute p1 {id}',conn)
127.0.0.1 - - [24/Sep/2026 05:10:36] "POST / HTTP/1.1" 200 -