1.Extract Data

In [41]:
import requests
import selenium

cities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Luxor",
    "Aswan"
]
list_cities=[]

url = "https://api.openweathermap.org/data/2.5/weather"

for city in cities:
    params = {
        "q": city,
        "appid": "6a13e61e853763292101962a026aa3e8",  
        "units": "metric"
    }

    response = requests.get(url, params=params)

    
    data = response.json()
    city_weather = {
            "city": city,
            "country": data["sys"]["country"],
            "temperature": data["main"]["temp"],
            "pressure": data["main"]["pressure"],
            "wind speed": data["wind"]["speed"],
            'humidity':data["main"]["humidity"]

        }
    list_cities.append(city_weather)
      


list_cities

[{'city': 'Cairo',
  'country': 'EG',
  'temperature': 32.42,
  'pressure': 1012,
  'wind speed': 4.12,
  'humidity': 33},
 {'city': 'Giza',
  'country': 'EG',
  'temperature': 32.41,
  'pressure': 1012,
  'wind speed': 3.33,
  'humidity': 30},
 {'city': 'Alexandria',
  'country': 'EG',
  'temperature': 28.98,
  'pressure': 1014,
  'wind speed': 3.09,
  'humidity': 54},
 {'city': 'Port Said',
  'country': 'EG',
  'temperature': 28.99,
  'pressure': 1012,
  'wind speed': 8.23,
  'humidity': 61},
 {'city': 'Suez',
  'country': 'EG',
  'temperature': 32.82,
  'pressure': 1011,
  'wind speed': 4.37,
  'humidity': 29},
 {'city': 'Ismailia',
  'country': 'EG',
  'temperature': 34.04,
  'pressure': 1011,
  'wind speed': 6.17,
  'humidity': 38},
 {'city': 'Mansoura',
  'country': 'DZ',
  'temperature': 24.79,
  'pressure': 1014,
  'wind speed': 3.09,
  'humidity': 48},
 {'city': 'Tanta',
  'country': 'EG',
  'temperature': 33.04,
  'pressure': 1012,
  'wind speed': 4.79,
  'humidity': 26},
 {'city': 'Luxor',
  'country': 'EG',
  'temperature': 39.03,
  'pressure': 1010,
  'wind speed': 3.6,
  'humidity': 16},
 {'city': 'Aswan',
  'country': 'EG',
  'temperature': 41.61,
  'pressure': 1009,
  'wind speed': 6.17,
  'humidity': 14}]

In [11]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/moaaz/Desktop/VS code/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/moaaz/Desktop/VS code/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 11.7 MB/s  0:00:01m0:00:010:01
Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 10.5 MB/s  0:00:01 eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

2.Transform

In [42]:
import pandas as pd
data = pd.DataFrame(list_cities)
data

         city country  temperature  pressure  wind speed  humidity
0       Cairo      EG        32.42      1012        4.12        33
1        Giza      EG        32.41      1012        3.33        30
2  Alexandria      EG        28.98      1014        3.09        54
3   Port Said      EG        28.99      1012        8.23        61
4        Suez      EG        32.82      1011        4.37        29
5    Ismailia      EG        34.04      1011        6.17        38
6    Mansoura      DZ        24.79      1014        3.09        48
7       Tanta      EG        33.04      1012        4.79        26
8       Luxor      EG        39.03      1010        3.60        16
9       Aswan      EG        41.61      1009        6.17        14

In [43]:
def fun (city):
    if city == 'Alexandria':
        return 'Upper Cairo'
    elif city == 'Suez':
        return 'Canal'
    elif city == 'Ismailia':
        return 'Canal'
    elif city == 'Port Said':
        return 'Canal'
    elif city == 'Cairo':
        return 'Greater Cairo'
    elif city == 'Giza':
        return 'Greater Cairo'
    elif city == 'Mansoura':
        return 'Delta'
    elif city == 'Tanta':
        return 'Delta'
    elif city == 'Luxor':
        return 'Lower Egypt'
    elif city == 'Aswan':
        return 'Lower Egypt'

In [44]:
data['Region']= data['city'].apply(fun)
data

,city,country,temperature,pressure,wind speed,humidity,Region
0,Cairo,EG,32.42,1012,4.12,33,Greater Cairo
1,Giza,EG,32.41,1012,3.33,30,Greater Cairo
2,Alexandria,EG,28.98,1014,3.09,54,Upper Cairo
3,Port Said,EG,28.99,1012,8.23,61,Canal
4,Suez,EG,32.82,1011,4.37,29,Canal
5,Ismailia,EG,34.04,1011,6.17,38,Canal
6,Mansoura,DZ,24.79,1014,3.09,48,Delta
7,Tanta,EG,33.04,1012,4.79,26,Delta
8,Luxor,EG,39.03,1010,3.60,16,Lower Egypt
9,Aswan,EG,41.61,1009,6.17,14,Lower Egypt

In [45]:
def tempcat(temp):
    if temp < 10:
        return 'Cold'
    elif temp >= 10 and temp < 20:
        return 'Mild'
    elif temp >= 20 and temp < 30:
        return 'Warm'
    else:
        return 'Hot'

In [35]:
data['TemperatureCategory']=data['temperature'].apply(tempcat)
data

,city,country,temperature,pressure,wind speed,humidity,Region,TemperatureCategory
0,Cairo,EG,32.42,1012,4.12,31,Greater Cairo,Hot
1,Giza,EG,32.41,1012,3.33,30,Greater Cairo,Hot
2,Alexandria,EG,28.98,1014,3.09,54,Upper Cairo,Warm
3,Port Said,EG,28.99,1012,8.23,61,Canal,Warm
4,Suez,EG,32.82,1011,4.37,29,Canal,Hot
5,Ismailia,EG,34.04,1011,6.17,38,Canal,Hot
6,Mansoura,DZ,24.79,1014,3.09,48,Delta,Warm
7,Tanta,EG,33.04,1012,4.79,26,Delta,Hot
8,Luxor,EG,39.03,1010,3.60,16,Lower Egypt,Hot
9,Aswan,EG,41.61,1009,6.17,14,Lower Egypt,Hot

In [37]:
def HumidityCategory(humidity):
    if humidity < 30:
        return 'Low'
    elif humidity >= 30 and humidity < 60:
        return 'Medium'
    else:
        return 'High'

In [39]:
data['HumidityCategory']=data['humidity'].apply(HumidityCategory)
data

,city,country,temperature,pressure,wind speed,humidity,Region,TemperatureCategory,HumidityCategory
0,Cairo,EG,32.42,1012,4.12,31,Greater Cairo,Hot,Medium
1,Giza,EG,32.41,1012,3.33,30,Greater Cairo,Hot,Medium
2,Alexandria,EG,28.98,1014,3.09,54,Upper Cairo,Warm,Medium
3,Port Said,EG,28.99,1012,8.23,61,Canal,Warm,High
4,Suez,EG,32.82,1011,4.37,29,Canal,Hot,Low
5,Ismailia,EG,34.04,1011,6.17,38,Canal,Hot,Medium
6,Mansoura,DZ,24.79,1014,3.09,48,Delta,Warm,Medium
7,Tanta,EG,33.04,1012,4.79,26,Delta,Hot,Low
8,Luxor,EG,39.03,1010,3.60,16,Lower Egypt,Hot,Low
9,Aswan,EG,41.61,1009,6.17,14,Lower Egypt,Hot,Low

3.Load

In [61]:
data_tuples = list(data.itertuples(index = None, name = None))

In [68]:
import pyodbc
conn = pyodbc.connect(                    
       "DRIVER={ODBC Driver 18 for SQL Server};"
       "SERVER=depi12462.database.windows.net;"
       "DATABASE=Depi;"
       "UID=sqladmin;"
       "PWD=Depi123#;"
       "Encrypt=yes;"
       "TrustServerCertificate=no;"
)
 
cursor = conn.cursor()

cursor.execute("""
create table moaazmoh2 (
    col1 varchar(100),
    col2 varchar(100),
    col3 varchar(100),
    col4 varchar(100),
    col5 varchar(100),
    col6 varchar(100),
    col7 varchar(100)
)
""")

conn.commit()
cursor.close()

In [66]:
print(data_tuples[0])
print(len(data_tuples[0]))

('Cairo', 'EG', 32.42, 1012, 4.12, 33, 'Greater Cairo')
7

In [70]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=depi12462.database.windows.net;"
    "DATABASE=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
    "Encrypt=yes;"
    "TrustServerCertificate=no;"
)

cursor = conn.cursor()

cursor.executemany(
    "insert into moaazmoh2 values (?,?,?,?,?,?,?)",
    data_tuples
)

conn.commit()
cursor.close()